### ISSUE TITLE
mutiple vps

### ISSUE THREAD

**Issue by Vatsalya-24** [cvg/VP-Estimation-with-Prior-Gravity#8]
the code is giving multiple vanishing point every time i run the code ,  it should give the master single vanishing point for an image

**Comment by rpautrat** [comment]
Hi, what do you call master vanishing point? Every natural image has multiple vanishing points, usually three in man-made environments, and sometimes more. This repository is returning the three dominant directions assuming a Manhattan world (one vertical vanishing point and two horizontal ones).

**Comment by Vatsalya-24** [comment]
Then how will i get those points? I want that I should get the single vp in 2d space

**Comment by Vatsalya-24** [comment]
But every time I run the function I am getting different vanishing points.

**Comment by rpautrat** [comment]
This code is based on RANSAC, which is a non deterministic algorithm. So yes, you will get different results each time. To get more consistent results , you can increase the number of RANSAC and refinement iterations, i.e. increasing `num_lo_steps` and `min_num_iterations_` here: https://github.com/cvg/VP-Estimation-with-Prior-Gravity/blob/fc154dd36e82b5ef8cc8a75d4d7e0b7ae2e2392c/vp_estimation_with_prior_gravity/solvers.py#L173-L175
This will however make the inference slower.
